name: hyip_lab
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  file_picker: ^9.2.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  animated_bottom_navigation_bar: ^1.4.0
  url_launcher: ^6.3.1
  flutter_widget_from_html: ^0.16.0
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  firebase_core: ^3.12.1
  connectivity_plus: ^6.1.3
  percent_indicator: ^4.2.4
  google_fonts: ^6.2.1
  awesome_dialog: ^3.2.1
  flutter_inappwebview: ^6.1.5
  json_annotation: any
  permission_handler: ^11.4.0
  flutter_spinkit: ^5.2.1
  open_file: ^3.5.10
  google_sign_in: ^6.3.0
  equatable: ^2.0.7
  country_picker: ^2.0.27
  country_pickers: ^3.0.1
  flutter_web3: ^2.1.9
  ethereum_addresses: ^1.0.2
  web3dart: ^2.6.1
  walletconnect_dart: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/game/
    - assets/images/onboard/
    - assets/images/logo/
    - assets/images/social/
    - assets/images/menu/
    - assets/images/bottom_nav/
    - assets/icons/home_menu_icon/
    - assets/icons/
    - assets/animation/
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf